### ISSUE TITLE
Won't convert labels.txt to labels.bed

### ISSUE THREAD

**Issue by HussainAther** [tdhock/PeakSegPipeline#2]
I have a `labels.txt` file that looks like this 

```
chr2L:72,965-73,182 peakStart
chr2L:73,183-74,241 peaks
chr2L:74,242-74,305 peakEnd

chr2L:11,011,984-11,012,154 peakStart
chr2L:11,012,278-11,012,441 peakEnd
```

but when I run `Rscript -e 'PeakSegPipeline::convert_labels("labels.txt")'`, I get the error

```
Error in order(chrom, chromStart, chromEnd) : object 'chrom' not found
Calls: <Anonymous> -> order
Execution halted
```

Have I labeled the `labels.txt` file incorrectly?

**Comment by tdhock** [comment]
Sorry for the un-informative error message. I just pushed a commit which will provide a more informative error message. https://github.com/tdhock/PeakSegPipeline/commit/0b41d741df598b16bd66362e304334d47129be67

Using this new code and your labels file I get:
```r
>     convert_labels(labels.txt)
Error in convert_labels(labels.txt) : 
  proj.dir=/tmp/Rtmpgbvfiy/file1274631302a4/labels/someLabels.txt should be a project directory with proj.dir/labels/*.txt files
> 
```
so your first problem is that the argument to convert_labels must be the project directory (not the labels file).

When I create a project directory proj.dir and then put your labels file under proj.dir/labels/someLabels.txt then I get the following:
```r
>     convert_labels(proj.dir)
Reading /tmp/Rtmpgbvfiy/file1274631302a4/labels/someLabels.txt
2 chunks, 5 label lines
  chrom chromStart chromEnd annotation sample.groups chunk.id
1 chr2L      72965    73182  peakStart                      2
2 chr2L      73183    74241      peaks                      2
3 chr2L      74242    74305    peakEnd                      2
4 chr2L   11011984 11012154  peakStart                      3
5 chr2L   11012278 11012441    peakEnd                      3
Error in convert_labels(proj.dir) : 
  need at least one sample group up for each positive label
> 
```
So as the new error message says, yes you do have an invalid labels file. The problem is that for each positive label (peaks, peakStart, peakEnd) you must specify at least one sample group with that label, and you have not specified any. For example this would be OK:
```
chr2L:72,965-73,182 peakStart bcell
chr2L:73,183-74,241 peaks bcell
chr2L:74,242-74,305 peakEnd bcell 

chr2L:11,011,984-11,012,154 peakStart bcell monocyte
chr2L:11,012,278-11,012,441 peakEnd bcell monocyte
```
which means the first chunk has a peak only in bcell samples, and the second chunk has a peak in both bcell and monocyte samples.

You may have another problem with "chr2L" -- is that a valid chromosome name in the genome that you are using? I would think you need to delete the L.

**Comment by HussainAther** [comment]
Thank you for this info. I'm using the dm6 fly genome so I have chromosomes like 2L and 2R. How do I run convert_labels with the fly genome?

**Comment by tdhock** [comment]
ok well if you really have a chromosome called chr2L then that should be
fine (as long as you use the same names in the problems.bed file and the
coverage.bigWig files)

**Comment by tdhock** [comment]
if it doesn't work for some reason (I have never tried it on the fly genome
but in theory it should work), please send me an example data set so I can
test/debug

**Comment by HussainAther** [comment]
working now .thanks!
